
package ir.taravatgroup.ezafekari2;

import java.io.IOException;
import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.pc.PCBA;
import anywheresoftware.b4a.pc.RDebug;
import anywheresoftware.b4a.pc.RemoteObject;
import anywheresoftware.b4a.pc.RDebug.IRemote;
import anywheresoftware.b4a.pc.Debug;
import anywheresoftware.b4a.pc.B4XTypes.B4XClass;
import anywheresoftware.b4a.pc.B4XTypes.DeviceClass;

public class shift_activity implements IRemote{
	public static shift_activity mostCurrent;
	public static RemoteObject processBA;
    public static boolean processGlobalsRun;
    public static RemoteObject myClass;
    public static RemoteObject remoteMe;
	public shift_activity() {
		mostCurrent = this;
	}
    public RemoteObject getRemoteMe() {
        return remoteMe;    
    }
    
	public static void main (String[] args) throws Exception {
		new RDebug(args[0], Integer.parseInt(args[1]), Integer.parseInt(args[2]), args[3]);
		RDebug.INSTANCE.waitForTask();

	}
    static {
        anywheresoftware.b4a.pc.RapidSub.moduleToObject.put(new B4XClass("shift_activity"), "ir.taravatgroup.ezafekari2.shift_activity");
	}

public boolean isSingleton() {
		return true;
	}
     public static RemoteObject getObject() {
		return myClass;
	 }

	public RemoteObject activityBA;
	public RemoteObject _activity;
    private PCBA pcBA;

	public PCBA create(Object[] args) throws ClassNotFoundException{
		processBA = (RemoteObject) args[1];
		activityBA = (RemoteObject) args[2];
		_activity = (RemoteObject) args[3];
        anywheresoftware.b4a.keywords.Common.Density = (Float)args[4];
        remoteMe = (RemoteObject) args[5];
		pcBA = new PCBA(this, shift_activity.class);
        main_subs_0.initializeProcessGlobals();
		return pcBA;
	}
public static RemoteObject __c = RemoteObject.declareNull("anywheresoftware.b4a.keywords.Common");
public static RemoteObject _pan_hed_shift = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lbl0 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh0 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez0 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no0 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p0 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _p1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p8 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb8 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p9 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb9 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p10 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb10 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p11 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb11 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p12 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb12 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p13 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb13 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p14 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb14 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p22 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb22 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p23 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb23 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p24 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb24 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p25 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb25 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p26 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb26 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p27 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb27 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p28 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb28 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p21 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb21 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p20 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb20 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p19 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb19 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p18 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb18 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p17 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb17 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p16 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb16 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p15 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb15 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p29 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb29 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p30 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb30 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p31 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb31 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p32 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb32 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p33 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb33 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p34 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb34 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p35 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb35 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p36 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb36 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p37 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb37 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p38 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb38 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p39 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb39 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p40 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb40 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p41 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb41 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _p42 = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lb42 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbl_moon_name = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _current_moon = RemoteObject.createImmutable(0);
public static RemoteObject _lb = null;
public static RemoteObject _pa = null;
public static RemoteObject _sh = null;
public static RemoteObject _ez = null;
public static RemoteObject _no = null;
public static RemoteObject _lbl_today_monasebat = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbl_today = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _index_i_today = RemoteObject.createImmutable(0);
public static RemoteObject _this_day = RemoteObject.createImmutable(0);
public static RemoteObject _this_year = RemoteObject.createImmutable(0);
public static RemoteObject _this_moon = RemoteObject.createImmutable(0);
public static RemoteObject _last_selected_itemtag = RemoteObject.createImmutable(0);
public static RemoteObject _selectedday_id = RemoteObject.createImmutable(0);
public static RemoteObject _sh42 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh41 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh40 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh39 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh38 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh37 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh36 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh29 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh30 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh31 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh32 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh33 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh34 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh35 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh28 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh21 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh14 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh13 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh20 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh27 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh26 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh19 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh12 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh11 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh18 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh25 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh24 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh17 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh10 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh9 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh16 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh23 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh22 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh15 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh8 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _sh1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _date = RemoteObject.declareNull("com.b4a.manamsoftware.PersianDate.ManamPersianDate");
public static RemoteObject _start_day = RemoteObject.createImmutable(0);
public static RemoteObject _ls_shift_moon = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _ls_tatili_moon = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _ls_note_moon = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _pan_all_setsift = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _ls_set_shift = RemoteObject.declareNull("anywheresoftware.b4a.objects.ListViewWrapper");
public static RemoteObject _et_num_roz = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _sp_noe_shift = RemoteObject.declareNull("anywheresoftware.b4a.objects.SpinnerWrapper");
public static RemoteObject _list_sift_olgo = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _lbl_hed_set_shift = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no8 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no9 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no10 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no11 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no12 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no13 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no14 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no22 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no23 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no24 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no25 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no26 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no27 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no28 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no21 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no20 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no19 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no18 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no17 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no16 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no15 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no29 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no30 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no31 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no32 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no33 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no34 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no35 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no36 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no37 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no38 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no39 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no40 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no41 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _no42 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez42 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez41 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez40 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez39 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez38 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez37 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez36 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez35 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez34 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez33 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez32 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez31 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez30 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez29 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez15 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez16 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez17 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez18 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez19 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez20 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez21 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez28 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez27 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez26 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez25 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez24 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez23 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez22 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez14 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez13 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez12 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez11 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez10 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez9 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez8 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _ez1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbl_morakhasi_day = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbl_ezafekari_day = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbl_note_day = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _et_note = RemoteObject.declareNull("anywheresoftware.b4a.objects.EditTextWrapper");
public static RemoteObject _pan_all_note = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _lbl_date_in_note = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _rspop_year = RemoteObject.declareNull("com.rootsoft.rspopupmenu.RSPopupMenu");
public static RemoteObject _rspop_mah = RemoteObject.declareNull("com.rootsoft.rspopupmenu.RSPopupMenu");
public static RemoteObject _rspop_roz = RemoteObject.declareNull("com.rootsoft.rspopupmenu.RSPopupMenu");
public static RemoteObject _rspop_year_end = RemoteObject.declareNull("com.rootsoft.rspopupmenu.RSPopupMenu");
public static RemoteObject _rspop_mah_end = RemoteObject.declareNull("com.rootsoft.rspopupmenu.RSPopupMenu");
public static RemoteObject _rspop_roz_end = RemoteObject.declareNull("com.rootsoft.rspopupmenu.RSPopupMenu");
public static RemoteObject _rspop_year_tagvim = RemoteObject.declareNull("com.rootsoft.rspopupmenu.RSPopupMenu");
public static RemoteObject _rspop_moon_tagvim = RemoteObject.declareNull("com.rootsoft.rspopupmenu.RSPopupMenu");
public static RemoteObject _lbl_years = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbl_mah = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbl_mah_tagid = RemoteObject.createImmutable(0);
public static RemoteObject _lbl_roz = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbl_roz_end = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbl_mah_end = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbl_mah_end_tagid = RemoteObject.createImmutable(0);
public static RemoteObject _lbl_years_end = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbl_taradod_day = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _lbl_year_tagvim = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
public static RemoteObject _scrol_v = RemoteObject.declareNull("anywheresoftware.b4a.objects.ScrollViewWrapper");
public static RemoteObject _dateutils = RemoteObject.declareNull("b4a.example.dateutils");
public static ir.taravatgroup.ezafekari2.main _main = null;
public static ir.taravatgroup.ezafekari2.myfunc _myfunc = null;
public static ir.taravatgroup.ezafekari2.dbcode _dbcode = null;
public static ir.taravatgroup.ezafekari2.fast_run_activity _fast_run_activity = null;
public static ir.taravatgroup.ezafekari2.calc_activity _calc_activity = null;
public static ir.taravatgroup.ezafekari2.comment_activity _comment_activity = null;
public static ir.taravatgroup.ezafekari2.darsad_activity _darsad_activity = null;
public static ir.taravatgroup.ezafekari2.eidi_activity _eidi_activity = null;
public static ir.taravatgroup.ezafekari2.ganon_activity _ganon_activity = null;
public static ir.taravatgroup.ezafekari2.hogog_activity _hogog_activity = null;
public static ir.taravatgroup.ezafekari2.info_activity _info_activity = null;
public static ir.taravatgroup.ezafekari2.morakhasi_activity _morakhasi_activity = null;
public static ir.taravatgroup.ezafekari2.payankar_activity _payankar_activity = null;
public static ir.taravatgroup.ezafekari2.setting_activity _setting_activity = null;
public static ir.taravatgroup.ezafekari2.setting_hogog_activity _setting_hogog_activity = null;
public static ir.taravatgroup.ezafekari2.show_gozaresh_activity _show_gozaresh_activity = null;
public static ir.taravatgroup.ezafekari2.starter _starter = null;
public static ir.taravatgroup.ezafekari2.bime_activity _bime_activity = null;
public static ir.taravatgroup.ezafekari2.httputils2service _httputils2service = null;
  public Object[] GetGlobals() {
		return new Object[] {"Activity",shift_activity.mostCurrent._activity,"bime_activity",Debug.moduleToString(ir.taravatgroup.ezafekari2.bime_activity.class),"calc_activity",Debug.moduleToString(ir.taravatgroup.ezafekari2.calc_activity.class),"comment_activity",Debug.moduleToString(ir.taravatgroup.ezafekari2.comment_activity.class),"current_moon",shift_activity._current_moon,"darsad_activity",Debug.moduleToString(ir.taravatgroup.ezafekari2.darsad_activity.class),"date",shift_activity.mostCurrent._date,"DateUtils",shift_activity.mostCurrent._dateutils,"dbCode",Debug.moduleToString(ir.taravatgroup.ezafekari2.dbcode.class),"eidi_activity",Debug.moduleToString(ir.taravatgroup.ezafekari2.eidi_activity.class),"et_note",shift_activity.mostCurrent._et_note,"et_num_roz",shift_activity.mostCurrent._et_num_roz,"EZ",shift_activity.mostCurrent._ez,"ez0",shift_activity.mostCurrent._ez0,"ez1",shift_activity.mostCurrent._ez1,"ez10",shift_activity.mostCurrent._ez10,"ez11",shift_activity.mostCurrent._ez11,"ez12",shift_activity.mostCurrent._ez12,"ez13",shift_activity.mostCurrent._ez13,"ez14",shift_activity.mostCurrent._ez14,"ez15",shift_activity.mostCurrent._ez15,"ez16",shift_activity.mostCurrent._ez16,"ez17",shift_activity.mostCurrent._ez17,"ez18",shift_activity.mostCurrent._ez18,"ez19",shift_activity.mostCurrent._ez19,"ez2",shift_activity.mostCurrent._ez2,"ez20",shift_activity.mostCurrent._ez20,"ez21",shift_activity.mostCurrent._ez21,"ez22",shift_activity.mostCurrent._ez22,"ez23",shift_activity.mostCurrent._ez23,"ez24",shift_activity.mostCurrent._ez24,"ez25",shift_activity.mostCurrent._ez25,"ez26",shift_activity.mostCurrent._ez26,"ez27",shift_activity.mostCurrent._ez27,"ez28",shift_activity.mostCurrent._ez28,"ez29",shift_activity.mostCurrent._ez29,"ez3",shift_activity.mostCurrent._ez3,"ez30",shift_activity.mostCurrent._ez30,"ez31",shift_activity.mostCurrent._ez31,"ez32",shift_activity.mostCurrent._ez32,"ez33",shift_activity.mostCurrent._ez33,"ez34",shift_activity.mostCurrent._ez34,"ez35",shift_activity.mostCurrent._ez35,"ez36",shift_activity.mostCurrent._ez36,"ez37",shift_activity.mostCurrent._ez37,"ez38",shift_activity.mostCurrent._ez38,"ez39",shift_activity.mostCurrent._ez39,"ez4",shift_activity.mostCurrent._ez4,"ez40",shift_activity.mostCurrent._ez40,"ez41",shift_activity.mostCurrent._ez41,"ez42",shift_activity.mostCurrent._ez42,"ez5",shift_activity.mostCurrent._ez5,"ez6",shift_activity.mostCurrent._ez6,"ez7",shift_activity.mostCurrent._ez7,"ez8",shift_activity.mostCurrent._ez8,"ez9",shift_activity.mostCurrent._ez9,"fast_run_activity",Debug.moduleToString(ir.taravatgroup.ezafekari2.fast_run_activity.class),"ganon_activity",Debug.moduleToString(ir.taravatgroup.ezafekari2.ganon_activity.class),"hogog_activity",Debug.moduleToString(ir.taravatgroup.ezafekari2.hogog_activity.class),"HttpUtils2Service",Debug.moduleToString(ir.taravatgroup.ezafekari2.httputils2service.class),"index_i_today",shift_activity._index_i_today,"info_activity",Debug.moduleToString(ir.taravatgroup.ezafekari2.info_activity.class),"last_selected_itemTag",shift_activity._last_selected_itemtag,"Lb",shift_activity.mostCurrent._lb,"lb1",shift_activity.mostCurrent._lb1,"lb10",shift_activity.mostCurrent._lb10,"lb11",shift_activity.mostCurrent._lb11,"lb12",shift_activity.mostCurrent._lb12,"lb13",shift_activity.mostCurrent._lb13,"lb14",shift_activity.mostCurrent._lb14,"lb15",shift_activity.mostCurrent._lb15,"lb16",shift_activity.mostCurrent._lb16,"lb17",shift_activity.mostCurrent._lb17,"lb18",shift_activity.mostCurrent._lb18,"lb19",shift_activity.mostCurrent._lb19,"lb2",shift_activity.mostCurrent._lb2,"lb20",shift_activity.mostCurrent._lb20,"lb21",shift_activity.mostCurrent._lb21,"lb22",shift_activity.mostCurrent._lb22,"lb23",shift_activity.mostCurrent._lb23,"lb24",shift_activity.mostCurrent._lb24,"lb25",shift_activity.mostCurrent._lb25,"lb26",shift_activity.mostCurrent._lb26,"lb27",shift_activity.mostCurrent._lb27,"lb28",shift_activity.mostCurrent._lb28,"lb29",shift_activity.mostCurrent._lb29,"lb3",shift_activity.mostCurrent._lb3,"lb30",shift_activity.mostCurrent._lb30,"lb31",shift_activity.mostCurrent._lb31,"lb32",shift_activity.mostCurrent._lb32,"lb33",shift_activity.mostCurrent._lb33,"lb34",shift_activity.mostCurrent._lb34,"lb35",shift_activity.mostCurrent._lb35,"lb36",shift_activity.mostCurrent._lb36,"lb37",shift_activity.mostCurrent._lb37,"lb38",shift_activity.mostCurrent._lb38,"lb39",shift_activity.mostCurrent._lb39,"lb4",shift_activity.mostCurrent._lb4,"lb40",shift_activity.mostCurrent._lb40,"lb41",shift_activity.mostCurrent._lb41,"lb42",shift_activity.mostCurrent._lb42,"lb5",shift_activity.mostCurrent._lb5,"lb6",shift_activity.mostCurrent._lb6,"lb7",shift_activity.mostCurrent._lb7,"lb8",shift_activity.mostCurrent._lb8,"lb9",shift_activity.mostCurrent._lb9,"lbl_date_in_note",shift_activity.mostCurrent._lbl_date_in_note,"lbl_ezafekari_day",shift_activity.mostCurrent._lbl_ezafekari_day,"lbl_hed_set_shift",shift_activity.mostCurrent._lbl_hed_set_shift,"lbl_mah",shift_activity.mostCurrent._lbl_mah,"lbl_mah_end",shift_activity.mostCurrent._lbl_mah_end,"lbl_mah_end_tagID",shift_activity._lbl_mah_end_tagid,"lbl_mah_tagID",shift_activity._lbl_mah_tagid,"lbl_moon_name",shift_activity.mostCurrent._lbl_moon_name,"lbl_morakhasi_day",shift_activity.mostCurrent._lbl_morakhasi_day,"lbl_note_day",shift_activity.mostCurrent._lbl_note_day,"lbl_roz",shift_activity.mostCurrent._lbl_roz,"lbl_roz_end",shift_activity.mostCurrent._lbl_roz_end,"lbl_taradod_day",shift_activity.mostCurrent._lbl_taradod_day,"lbl_today",shift_activity.mostCurrent._lbl_today,"lbl_today_monasebat",shift_activity.mostCurrent._lbl_today_monasebat,"lbl_year_tagvim",shift_activity.mostCurrent._lbl_year_tagvim,"lbl_years",shift_activity.mostCurrent._lbl_years,"lbl_years_end",shift_activity.mostCurrent._lbl_years_end,"lbl0",shift_activity.mostCurrent._lbl0,"list_sift_olgo",shift_activity.mostCurrent._list_sift_olgo,"ls_note_moon",shift_activity.mostCurrent._ls_note_moon,"ls_set_shift",shift_activity.mostCurrent._ls_set_shift,"ls_shift_moon",shift_activity.mostCurrent._ls_shift_moon,"ls_tatili_moon",shift_activity.mostCurrent._ls_tatili_moon,"Main",Debug.moduleToString(ir.taravatgroup.ezafekari2.main.class),"morakhasi_activity",Debug.moduleToString(ir.taravatgroup.ezafekari2.morakhasi_activity.class),"myfunc",Debug.moduleToString(ir.taravatgroup.ezafekari2.myfunc.class),"NO",shift_activity.mostCurrent._no,"no0",shift_activity.mostCurrent._no0,"no1",shift_activity.mostCurrent._no1,"no10",shift_activity.mostCurrent._no10,"no11",shift_activity.mostCurrent._no11,"no12",shift_activity.mostCurrent._no12,"no13",shift_activity.mostCurrent._no13,"no14",shift_activity.mostCurrent._no14,"no15",shift_activity.mostCurrent._no15,"no16",shift_activity.mostCurrent._no16,"no17",shift_activity.mostCurrent._no17,"no18",shift_activity.mostCurrent._no18,"no19",shift_activity.mostCurrent._no19,"no2",shift_activity.mostCurrent._no2,"no20",shift_activity.mostCurrent._no20,"no21",shift_activity.mostCurrent._no21,"no22",shift_activity.mostCurrent._no22,"no23",shift_activity.mostCurrent._no23,"no24",shift_activity.mostCurrent._no24,"no25",shift_activity.mostCurrent._no25,"no26",shift_activity.mostCurrent._no26,"no27",shift_activity.mostCurrent._no27,"no28",shift_activity.mostCurrent._no28,"no29",shift_activity.mostCurrent._no29,"no3",shift_activity.mostCurrent._no3,"no30",shift_activity.mostCurrent._no30,"no31",shift_activity.mostCurrent._no31,"no32",shift_activity.mostCurrent._no32,"no33",shift_activity.mostCurrent._no33,"no34",shift_activity.mostCurrent._no34,"no35",shift_activity.mostCurrent._no35,"no36",shift_activity.mostCurrent._no36,"no37",shift_activity.mostCurrent._no37,"no38",shift_activity.mostCurrent._no38,"no39",shift_activity.mostCurrent._no39,"no4",shift_activity.mostCurrent._no4,"no40",shift_activity.mostCurrent._no40,"no41",shift_activity.mostCurrent._no41,"no42",shift_activity.mostCurrent._no42,"no5",shift_activity.mostCurrent._no5,"no6",shift_activity.mostCurrent._no6,"no7",shift_activity.mostCurrent._no7,"no8",shift_activity.mostCurrent._no8,"no9",shift_activity.mostCurrent._no9,"p0",shift_activity.mostCurrent._p0,"p1",shift_activity.mostCurrent._p1,"p10",shift_activity.mostCurrent._p10,"p11",shift_activity.mostCurrent._p11,"p12",shift_activity.mostCurrent._p12,"p13",shift_activity.mostCurrent._p13,"p14",shift_activity.mostCurrent._p14,"p15",shift_activity.mostCurrent._p15,"p16",shift_activity.mostCurrent._p16,"p17",shift_activity.mostCurrent._p17,"p18",shift_activity.mostCurrent._p18,"p19",shift_activity.mostCurrent._p19,"p2",shift_activity.mostCurrent._p2,"p20",shift_activity.mostCurrent._p20,"p21",shift_activity.mostCurrent._p21,"p22",shift_activity.mostCurrent._p22,"p23",shift_activity.mostCurrent._p23,"p24",shift_activity.mostCurrent._p24,"p25",shift_activity.mostCurrent._p25,"p26",shift_activity.mostCurrent._p26,"p27",shift_activity.mostCurrent._p27,"p28",shift_activity.mostCurrent._p28,"p29",shift_activity.mostCurrent._p29,"p3",shift_activity.mostCurrent._p3,"p30",shift_activity.mostCurrent._p30,"p31",shift_activity.mostCurrent._p31,"p32",shift_activity.mostCurrent._p32,"p33",shift_activity.mostCurrent._p33,"p34",shift_activity.mostCurrent._p34,"p35",shift_activity.mostCurrent._p35,"p36",shift_activity.mostCurrent._p36,"p37",shift_activity.mostCurrent._p37,"p38",shift_activity.mostCurrent._p38,"p39",shift_activity.mostCurrent._p39,"p4",shift_activity.mostCurrent._p4,"p40",shift_activity.mostCurrent._p40,"p41",shift_activity.mostCurrent._p41,"p42",shift_activity.mostCurrent._p42,"p5",shift_activity.mostCurrent._p5,"p6",shift_activity.mostCurrent._p6,"p7",shift_activity.mostCurrent._p7,"p8",shift_activity.mostCurrent._p8,"p9",shift_activity.mostCurrent._p9,"PA",shift_activity.mostCurrent._pa,"pan_all_note",shift_activity.mostCurrent._pan_all_note,"pan_all_setSift",shift_activity.mostCurrent._pan_all_setsift,"pan_hed_shift",shift_activity.mostCurrent._pan_hed_shift,"payankar_activity",Debug.moduleToString(ir.taravatgroup.ezafekari2.payankar_activity.class),"rsPOP_mah",shift_activity.mostCurrent._rspop_mah,"rsPOP_mah_end",shift_activity.mostCurrent._rspop_mah_end,"rsPOP_moon_tagvim",shift_activity.mostCurrent._rspop_moon_tagvim,"rsPOP_roz",shift_activity.mostCurrent._rspop_roz,"rsPOP_roz_end",shift_activity.mostCurrent._rspop_roz_end,"rsPOP_year",shift_activity.mostCurrent._rspop_year,"rsPOP_year_end",shift_activity.mostCurrent._rspop_year_end,"rsPOP_year_tagvim",shift_activity.mostCurrent._rspop_year_tagvim,"scrol_v",shift_activity.mostCurrent._scrol_v,"selectedDay_id",shift_activity._selectedday_id,"setting_activity",Debug.moduleToString(ir.taravatgroup.ezafekari2.setting_activity.class),"setting_hogog_activity",Debug.moduleToString(ir.taravatgroup.ezafekari2.setting_hogog_activity.class),"SH",shift_activity.mostCurrent._sh,"sh0",shift_activity.mostCurrent._sh0,"sh1",shift_activity.mostCurrent._sh1,"sh10",shift_activity.mostCurrent._sh10,"sh11",shift_activity.mostCurrent._sh11,"sh12",shift_activity.mostCurrent._sh12,"sh13",shift_activity.mostCurrent._sh13,"sh14",shift_activity.mostCurrent._sh14,"sh15",shift_activity.mostCurrent._sh15,"sh16",shift_activity.mostCurrent._sh16,"sh17",shift_activity.mostCurrent._sh17,"sh18",shift_activity.mostCurrent._sh18,"sh19",shift_activity.mostCurrent._sh19,"sh2",shift_activity.mostCurrent._sh2,"sh20",shift_activity.mostCurrent._sh20,"sh21",shift_activity.mostCurrent._sh21,"sh22",shift_activity.mostCurrent._sh22,"sh23",shift_activity.mostCurrent._sh23,"sh24",shift_activity.mostCurrent._sh24,"sh25",shift_activity.mostCurrent._sh25,"sh26",shift_activity.mostCurrent._sh26,"sh27",shift_activity.mostCurrent._sh27,"sh28",shift_activity.mostCurrent._sh28,"sh29",shift_activity.mostCurrent._sh29,"sh3",shift_activity.mostCurrent._sh3,"sh30",shift_activity.mostCurrent._sh30,"sh31",shift_activity.mostCurrent._sh31,"sh32",shift_activity.mostCurrent._sh32,"sh33",shift_activity.mostCurrent._sh33,"sh34",shift_activity.mostCurrent._sh34,"sh35",shift_activity.mostCurrent._sh35,"sh36",shift_activity.mostCurrent._sh36,"sh37",shift_activity.mostCurrent._sh37,"sh38",shift_activity.mostCurrent._sh38,"sh39",shift_activity.mostCurrent._sh39,"sh4",shift_activity.mostCurrent._sh4,"sh40",shift_activity.mostCurrent._sh40,"sh41",shift_activity.mostCurrent._sh41,"sh42",shift_activity.mostCurrent._sh42,"sh5",shift_activity.mostCurrent._sh5,"sh6",shift_activity.mostCurrent._sh6,"sh7",shift_activity.mostCurrent._sh7,"sh8",shift_activity.mostCurrent._sh8,"sh9",shift_activity.mostCurrent._sh9,"show_gozaresh_activity",Debug.moduleToString(ir.taravatgroup.ezafekari2.show_gozaresh_activity.class),"sp_noe_shift",shift_activity.mostCurrent._sp_noe_shift,"start_day",shift_activity._start_day,"Starter",Debug.moduleToString(ir.taravatgroup.ezafekari2.starter.class),"this_day",shift_activity._this_day,"this_moon",shift_activity._this_moon,"this_year",shift_activity._this_year};
}
}